#!/usr/bin/env python3
"""Writes every rendition of the Qoriqchi mark from one geometry.

The mark is the session ring with a bookmark ribbon for the Q's tail: the session
holds, and reaching for a blocked app opens a book. Coordinates are on Android's
108-unit adaptive-icon grid, of which the launcher shows the middle 72.

Run from the repository root:
  python3 scripts/brand/gen_mark.py          vector drawables only
  python3 scripts/brand/gen_mark.py --png    also the PNG fallbacks and in-app mark
                                             (needs Google Chrome and Pillow)
"""

import math
import os
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
RES = os.path.join(REPO, "android", "app", "src", "main", "res")

CX, CY = 51.95, 51.55               # ring centre, nudged up-left so the tail balances it
R, SW = 14.35, 5.75                 # ring radius (stroke centre) and stroke
W = 6.6                             # ribbon width
START, END, NOTCH = 5.7, 27.1, 3.9  # along the 45° axis from the ring centre
YELLOW, NAVY = "#FFFFC400", "#071426"



def geometry(scale=1.0, ox=0.0, oy=0.0, gap=1.25):
    T = lambda x, y: (ox + x*scale, oy + y*scale)
    f = lambda p: f"{p[0]:.2f},{p[1]:.2f}"
    ux = uy = math.sqrt(0.5); px, py = -uy, ux
    pt = lambda s, t: T(CX + ux*s + px*t, CY + uy*s + py*t)
    h = W/2
    # Two half arcs, closed: a single near-full arc leaves a hairline seam at 24dp.
    top, bottom, r = T(CX, CY - R), T(CX, CY + R), f"{R*scale:.2f},{R*scale:.2f}"
    ring = f"M{f(top)} A{r} 0,1 1,{f(bottom)} A{r} 0,1 1,{f(top)} Z"
    rib = [pt(START,-h), pt(END,-h), pt(END-NOTCH,0), pt(END,h), pt(START,h)]
    ribbon = "M" + " L".join(map(f, rib)) + " Z"
    # Clip = everything minus a band around the ribbon. The band is wound the
    # opposite way to the outer rectangle, so the non-zero rule leaves it out.
    g = gap
    band = [pt(START-g,-h-g), pt(START-g,h+g), pt(END+g,h+g), pt(END+g,-h-g)]
    a, b = T(-200,-200), T(400,400)
    clip = (f"M{f(a)} L{b[0]:.2f},{a[1]:.2f} L{f(b)} L{a[0]:.2f},{b[1]:.2f} Z "
            + "M" + " L".join(map(f, band)) + " Z")
    return ring, ribbon, clip, SW*scale


def vector(path, size, viewport, color, gap, scale=1.0, ox=0.0, oy=0.0, header="", tint="", back=""):
    ring, ribbon, clip, sw = geometry(scale, ox, oy, gap)
    if back:
        back = f'''
    <path
        android:pathData="{back}"
        android:fillColor="#FF071426" />'''
    open(path, "w").write(f'''<?xml version="1.0" encoding="utf-8"?>
{header}<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size}dp"
    android:height="{size}dp"
    android:viewportWidth="{viewport}"
    android:viewportHeight="{viewport}"{tint}>{back}
    <group>
        <clip-path android:pathData="{clip}" />
        <path
            android:pathData="{ring}"
            android:fillColor="#00000000"
            android:strokeColor="{color}"
            android:strokeWidth="{sw:.2f}" />
    </group>
    <path
        android:pathData="{ribbon}"
        android:fillColor="{color}" />
</vector>
''')


def svg(viewbox, color, gap, bg=None, shape=None, scale=1.0, ox=0.0, oy=0.0):
    ring, ribbon, clip, sw = geometry(scale, ox, oy, gap)
    back = ""
    if bg:
        x, y, w, h = viewbox
        back = (f'<circle cx="{x+w/2}" cy="{y+h/2}" r="{w/2}" fill="{bg}"/>' if shape == "circle"
                else f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{w*0.17}" fill="{bg}"/>')
    vb = " ".join(map(str, viewbox))
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}" width="100%" height="100%">{back}'
            f'<clipPath id="k"><path d="{clip}"/></clipPath>'
            f'<path d="{ring}" fill="none" stroke="{color}" stroke-width="{sw}" clip-path="url(#k)"/>'
            f'<path d="{ribbon}" fill="{color}"/></svg>')



def write_vectors():
    vector(f"{RES}/drawable/ic_launcher_foreground.xml", 108, 108, YELLOW, 1.25,
           header="<!-- The Qoriqchi mark: the session ring, with a bookmark ribbon for the Q's\n     tail. Generated by scripts/brand/gen_mark.py; edit the geometry there. -->\n")
    # Status-bar icons are masked to one colour; the mark is centred and scaled to 20dp.
    s = 20 / 38.7
    vector(f"{RES}/drawable/ic_notification.xml", 24, 24, "#FFFFFFFF", 2.0, s, 12 - 54.1*s, 12 - 53.7*s,
           header="<!-- Status bar icons are masked to a single colour, so this is the mark in flat\n     white on transparent. Generated by scripts/brand/gen_mark.py. -->\n",
           tint='\n    android:tint="#FFFFFFFF"')

    # API 24–25 have no adaptive icons; mipmap-anydpi draws the whole shape, with the
    # mark at the share of the shape it has inside an adaptive icon's visible 72.
    k = 100 / 72
    LEGACY = "<!-- Pre-adaptive launcher icon (API 24-25). Generated by scripts/brand/gen_mark.py. -->\n"
    vector(f"{RES}/mipmap-anydpi/ic_launcher.xml", 108, 108, YELLOW, 1.25, k, 54 - 54*k, 54 - 54*k, header=LEGACY,
           back="M22,4 H86 A18,18 0,0 1,104 22 V86 A18,18 0,0 1,86 104 H22 A18,18 0,0 1,4 86 V22 A18,18 0,0 1,22 4 Z")
    vector(f"{RES}/mipmap-anydpi/ic_launcher_round.xml", 108, 108, YELLOW, 1.25, k, 54 - 54*k, 54 - 54*k, header=LEGACY,
           back="M54,4 A50,50 0,1 1,53.99 4 Z")


def write_pngs():
    # Density PNGs for any launcher that skips mipmap-anydpi; same art as the vectors. launcher (API 24–25): the full shape, cropped to the adaptive icon's visible 72.
    svgs = {
        "legacy": svg((18, 18, 72, 72), "#FFC400", 1.25, NAVY, "square"),
        "legacy_round": svg((18, 18, 72, 72), "#FFC400", 1.25, NAVY, "circle"),
        # In-app mark: white on transparent, tinted by React Native; tight crop.
        "brand": svg((32.75, 32.35, 42.7, 42.7), "#FFFFFF", 1.6),
    }
    from PIL import Image
    chrome = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
    with tempfile.TemporaryDirectory() as tmp:
        big = {}
        for name, markup in svgs.items():
            page, shot = os.path.join(tmp, name + ".html"), os.path.join(tmp, name + ".png")
            with open(page, "w") as handle:
                handle.write('<html><body style="margin:0;background:transparent">'
                             f'<div style="width:1024px;height:1024px">{markup}</div></body></html>')
            subprocess.run([chrome, "--headless=new", "--disable-gpu", "--hide-scrollbars",
                            "--default-background-color=00000000", "--force-device-scale-factor=1",
                            "--window-size=1024,1024", f"--screenshot={shot}", "file://" + page],
                           check=True, capture_output=True)
            big[name] = Image.open(shot).convert("RGBA")
        for density, px in {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}.items():
            for name, file in (("legacy", "ic_launcher"), ("legacy_round", "ic_launcher_round")):
                big[name].resize((px, px), Image.LANCZOS).save(
                    os.path.join(RES, f"mipmap-{density}", file + ".png"), optimize=True)
        for suffix, px in {"": 48, "@2x": 96, "@3x": 144}.items():
            big["brand"].resize((px, px), Image.LANCZOS).save(
                os.path.join(REPO, "src", "assets", f"brand-mark{suffix}.png"), optimize=True)


if __name__ == "__main__":
    write_vectors()
    if "--png" in sys.argv:
        write_pngs()
